config/routes.rb
Rails.application.routes.draw do
	root 'main_page#home'
	get 		'top_list' 	=> 'main_page#top_list'
	get 		'sign_up' 	=> 'users#new'
	get 		'posts/new'
	get			'posts/show'
	get 		'login'			=> 'sessions#new'
	post 		'login'			=> 'sessions#create'
	delete 	'logout'		=> 'sessions#destroy'
	resources :users
	resources :posts do
		member do
			post 'like'
		end
		resources :comments, :only => [:create]
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :likes, as: :likeable
	has_many :comments
	before_save { title.upcase! }
	default_scope -> { order(created_at: :desc) }
	scope :toplist, -> { order(likes_count: :desc)}
	validates :user_id, presence: true
	validates :avatar, attachment_presence: true
	validates_attachment :avatar, content_Type: { content_type: ["image/jpeg",
																								"image/png", "image/gif"] }
	validates :title, presence: true, length: { maximum: 30, minimum: 4 }
	has_attached_file :avatar, styles: { large: "600x", medium: "300x300>",
																			 thumb: "100x100>" },
														 default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validate :avatar_size

	def feed
		posts
	end

	private

		# Validates the size of an uploaded image.
		def avatar_size
			unless avatar.size.nil?
				if avatar.size > 5.megabytes
					errors.add(:picture, "should be less than 5MB")
				end
			end
		end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	def show
		@post= Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			flash[:success] = "Post added"
			redirect_to root_path
		else
			render 'posts/new'
		end
	end

	def destroy
		post_destroy = Post.find(params[:id])
		post_destroy.destroy
		flash[:success] = "Post deleted"
		redirect_to request.referrer || root_url
	end

	def like
		@post = Post.find(params[:id])
		if @like = Like.find_by(likeable: @post, user: current_user)
			#Like.find_by(likeable: @post, user: current_user, like: true).destroy
			@like.destroy
			respond_to do |format|
				format.html {
					flash[:success] = "Like Updated!"
					redirect_to :back
				}
				format.js
				end
		else
			Like.create(likeable: @post, user: current_user, like: true)
			respond_to do |format|
				format.html {
					flash[:success] = "Like Updated!"
					redirect_to :back
				}
				format.js
			end
		end
	end

	#def like
	#	post = Post.find(params[:id])
	#	if Like.find_by(likeable: post)
	#		Like.find_by(likeable: post).destroy
	#		flash[:success] = "Post unliked!"
	#		redirect_to :back
	#	else
	#		Like.create(likeable: post, user: current_user, like: params[:like])
	#		flash[:success] = "Post liked!"
	#		redirect_to :back
	#	end
	#end

	private

		def post_params
			params.require(:post).permit(:title, :avatar)
		end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<span class="like">
  <span class="like_<%= post.id %>">
    <%= link_to "Like", like_post_path(post, like: true), method: 'post', remote: true %>
  </span>
</span>

app/views/posts/_post.html.erb
<li class="post">
	<span class="user"><%= link_to post.user.name, post.user %></span>
	<br>
	<span class="title"><%= link_to post.title, post %></span>
	<br>
	<span class="ava"><%= link_to(image_tag(post.avatar(:large)), post) %></span>
	<br>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago.
		<% if logged_in? && current_user.admin? %>
			<%= link_to "delete", post, method: :delete,
																	data: { confirm: "You sure?" } %>
		<% end %>
		<%= link_to "Comments (#{post.comments.count})", post %>
		<span class="likes">
			<% if logged_in? %>
				<% if !current_user.likes?(current_user, post) %>
					<span class="like_<%= post.id %>">
						<%= render 'posts/like', post: post %>
						</span>
				<% else %>
					<span class="unlike_<%= post.id %>">
						<%= render 'posts/unlike', post: post %>
					</span>
				<% end %>
				<span id="likers">
					<span id="likers_<%= post.id %>">
						(<%= pluralize( post.likes.size, "like") %>)
					</span>
				</span>
			<% else %>
				<%= link_to "Like", login_path,
					  data: { confirm: "You need to log in to like" } %>
				(<%= pluralize( post.likes.size, "like") %>)
			<% end %>
		</span>
	</span>
</li>

app/views/posts/_unlike.html.erb
<span class="unlike">
  <span class="unlike_<%= post.id %>">
    <%= link_to "Unlike", like_post_path(post, like: false), method: 'post', remote: true %>
  </span>
</span>

app/views/posts/like.js.erb
<% if Like.find_by(likeable: @post, user: current_user) %>
  $(".like_<%= @post.id %>").html("<%= escape_javascript(render 'posts/unlike', post: @post) %>");
<% else %>
  $(".unlike_<%= @post.id %>").html("<%= escape_javascript(render 'posts/like', post: @post) %>");
<% end %>

$("#likers_<%= @post.id %>").html(" (<%= pluralize( @post.likes.count, "like") %>) ");

app/views/posts/new.html.erb
<% provide(:title, "Add") %>
<div id="add">
	<%= form_for @post, :html => {:multipart => true} do |f|%>
		<%= render 'shared/error_messages', object: f.object %>
		<br>
		<h1>Add a new post</h1>
		<%= f.text_field :title, placeholder: "Title of the post..." %>
		<br><br>
		<span id="browse">
		<%= f.file_field :avatar %>
		</span>
		<br><br>
		<%= f.submit "Post" %>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="show_posts">
  <ol class="posts">
  <%= render @post %>
  </ol>
</div>
<h2>Comments</h2>
<% if logged_in?  %>
  <%= form_for [@post, Comment.new] do |f| %>
          <p>
                  <%= f.text_area :body %>
          </p>
          <p><%= f.submit "Add comment" %></p>
  <% end %>
<% else %>
  <h3>You have to be logged in to comment - <%= link_to "Log in", login_path %></h3>
<% end %>
<div id="comments">
  <%= render :partial => @post.comments %>
</div>