config/routes.rb
Rails.application.routes.draw do
	root 'main_page#home'
	get 		'top_list' 	=> 'main_page#top_list'
	get 		'sign_up' 	=> 'users#new'
	get 		'posts/new'
	get			'posts/show'
	get 		'login'			=> 'sessions#new'
	post 		'login'			=> 'sessions#create'
	delete 	'logout'		=> 'sessions#destroy'
	resources :users
	resources :posts do
		member do
			post 'like'
		end
		resources :comments, :only => [:create]
	end
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<div id="left">Quba - your daily dose of fun cats pictures.</div>
		<div id="right">
			<a href="https://www.facebook.com" target="_blank" 
			style="font-weight: bold">Jakub Kopyś</a> &copy;
		 all rights reserved.
		</div>
	</small>
</div>

app/views/layouts/_header.html.erb
<header id="topbar">
	<ul>
		<div class="option_logo"><%= link_to 'Quba', root_path %></div>
		<% if logged_in? %>
			<div class="dropdown">
			<ul>
				<li>
					<%= link_to 'Account', current_user%>
					<ul>
						<li class="nav-item">
							<%= link_to 'Profile', user_path(current_user) %>
						</li>
						<li class="nav-item"><%= link_to 'Settings',
																		 edit_user_path(current_user) %></li>
						<li class="nav-item logout">
							<%= link_to('Log out', logout_path, method: "delete" )%>
						</li>
					</ul>
				</li>
			<ul>
			</div>
			<div class="option">
				<%= link_to('Users', users_path)%>
			</div>
		<% end %>
		<div class="option"><%= link_to('Top List', top_list_path) %></div>
		<div class="option"><%= link_to('Random', Post.offset(rand(Post.count)).first)%></div>
		<% if !logged_in? %>
			<div class="option"><%= link_to('Log In', login_path )%></div>
		<% end %>
		<% if logged_in? %>
			<div class="option">
				<%= link_to('Add', '/posts/new')%>
			</div>
		<% end %>
	</ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all',
							 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |message_type, message| %>
			<div class="alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>